/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: [Your Name or Author]
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: [Source URL if available]
Title: Python logo
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

const PythonLogo = (props) => {
  const { nodes, materials } = useGLTF('/models/python.glb'); // Update to Python GLTF path

  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Python-Logo_Geometry_0'].geometry} // Replace with correct node name
          material={materials['Python-Logo_Material_0']} // Replace with correct material name
          position={[0, 7.935, 18.102]} // Adjust as needed
          rotation={[0, 0, -Math.PI / 2]} // Adjust as needed
          scale={[39.166, 39.166, 52.734]} // Adjust as needed
        />
      </group>
    </group>
  );
};

useGLTF.preload('/models/python.glb'); // Preload the Python GLTF file

export default PythonLogo;
